### ISSUE TITLE
Card images are not showing

### ISSUE THREAD

**Issue by danieldunderfelt** [exane/gwent#12]
Hi!

First of all, this is awesome! Thanks for the effort.

So I pulled the repo and got everything up and running. I can connect to games, hear music and so forth, but no cards are visible. I inspected the card elements, but found no reference to any images. Is this still work in progress, is something broken or have I done something wrong? The gulp tasks run fine, and graphicsmagick is working.

Thanks!

**Comment by exane** [comment]
Hey!

The problem here is the css-sprite-generator. It generates the css in uppercase file-extensions while the actual sprites are in lowercase.

To fix it you have to change the sprite extensions in ./public/build/ to uppercase or you open cards.css in ./public/build/ and set the extensions to lowercase.

(I still don't know why the sprite-css-generator makes the extension to uppercase. Can't find any options well.)

Anyway, I'm glad you like it!

**Comment by devfake** [comment]
Well played Daniel :P Thank you!

**Comment by danieldunderfelt** [comment]
Yeah same! Gwent turned out to be really fun. That monster deck is killer!
